export default [
  {
    id: 1,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: false,
    group: "O+",
    gender: "male",
    district: "Dhaka",
    photo: null,
    donated: 11,
  },
  {
    id: 2,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 20,
  },
  {
    id: 3,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 0,
  },
  {
    id: 4,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: false,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 4,
  },
  {
    id: 5,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 18,
  },
  {
    id: 6,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 9,
  },
  {
    id: 7,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: false,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 4,
  },
  {
    id: 8,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 5,
  },
  {
    id: 9,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 6,
  },
  {
    id: 10,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: false,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 7,
  },
  {
    id: 11,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 1,
  },
  {
    id: 12,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: true,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 13,
  },
  {
    id: 13,
    name: "Shihab Shohaul",
    age: "18",
    phone: "01950743811",
    eligible: false,
    group: "AB+",
    gender: "male",
    photo: null,
    district: "Dhaka",
    donated: 25,
  },
]
