export default [
  {
    _id: "1",
    gender: "male",
    firstName: "Abdullah",
    lastName: "Al Fahim",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "ENT, General Physician, Covid Unit",
    profilePic:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fGRvY3RvcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Anger Management", "Depression", "Domestic Violence"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 600,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 946,
    rating: 5,
  },
  {
    _id: "2",
    gender: "female",
    firstName: "Chang",
    lastName: "Chung",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "GNT, Ophthalmologist, Unit 44",
    profilePic:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZG9jdG9yfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Pocha Hagu", "Fever", "Domestic Violence"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 250,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 202,
    rating: 4.8,
  },
  {
    _id: "3",
    gender: "male",
    firstName: "MD Miyad",
    lastName: "Hossain",
    isOnline: false,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "CNN, GizGizLogist, Unit 96",
    profilePic:
      "https://images.unsplash.com/photo-1622475442837-ab958c6a1c64?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzZ8fGRvY3RvcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["কোষ্ঠকাঠিন্য", "Game Addiction", "Domestic Violence"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 250,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 202,
    rating: 4.0,
  },
  {
    _id: "4",
    gender: "male",
    firstName: "Ali",
    lastName: "Abdaal",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "CNN, DhurobaiLogist, Unit 25",
    profilePic:
      "https://lits.me/wp-content/uploads/2021/04/Ali-Abdaal-300x300.png",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Youtube (Eh?)", "Productivity", "I Dunno Yaar"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 999,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 404,
    rating: 3.5,
  },
  {
    _id: "5",
    gender: "male",
    firstName: "Minhaj Rahat",
    lastName: "Abdaal",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "CNN, DhurobaiLogist, Unit 25",
    profilePic:
      "https://images.unsplash.com/photo-1612276529418-52e6ad86ee1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Youtube (Eh?)", "Productivity", "I Dunno Yaar"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 999,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 404,
    rating: 3.5,
  },
  {
    _id: "6",
    gender: "male",
    firstName: "Ali",
    lastName: "Abdaal",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "CNN, DhurobaiLogist, Unit 25",
    profilePic:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fGRvY3RvcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Youtube (Eh?)", "Productivity", "I Dunno Yaar"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 999,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 404,
    rating: 3.5,
  },
  {
    _id: "7",
    gender: "female",
    firstName: "Chang",
    lastName: "Chung",
    isOnline: true,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "GNT, Ophthalmologist, Unit 44",
    profilePic:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZG9jdG9yfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Coding (Hell Yeah)", "Fever", "Domestic Violence"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 250,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 202,
    rating: 4.8,
  },
  {
    _id: "8",
    gender: "male",
    firstName: "MD Miyad",
    lastName: "Hossain",
    isOnline: false,
    email: "test@test.com",
    mobile: "01950743855",
    dob: "1976-12-15",
    bio: "CNN, GizGizLogist, Unit 96",
    profilePic:
      "https://images.unsplash.com/photo-1622475442837-ab958c6a1c64?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzZ8fGRvY3RvcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    profileDesc:
      "Dr Mahububul Alam Kulkarni belives that once you start being more aware of your thoughts and actions, you will start appreciating life in a new way. This is why he specializes in depression, mood disorders, sexual disorders and anxiety disorders, because he feels that every person is capable of bringing about a change from within. His process is supportive, but aimed at direct interaction to help the patient bring about a visible change in himself or herself.",
    specializations: ["Kidny", "Heart"],
    license: [
      "Registration No. MMC 2009093394, Medical Council of India 09/33958",
      "2006113358 Maharashtra Medical Council, 2006",
    ],
    language: ["Hindi", " English", " Telugu", "Hagu"],
    experience: [
      {
        company: "Apollo Hospital chennai",
        years: "10 years",
        desc: "Gt when then formula was invented",
        awards: "This is the test award ",
      },
      {
        company: "Apollo Hospital Mumbai",
        years: "15 years",
        desc: "Gt when then formula was Used",
        awards: "This is the test award -2",
      },
    ],
    communication: [
      {
        mode: "Audio",
        cost: 250,
        currency: "INR",
        icon: "telephone.png",
        location: "-1",
      },
      {
        mode: "Video",
        cost: 800,
        currency: "INR",
        icon: "video.png",
        location: "-1",
      },
      {
        mode: "Chat",
        cost: 300,
        currency: "INR",
        icon: "chat.png",
        location: "-1",
      },
    ],
    conversations: 202,
    rating: 4.0,
  },
]
